/* Generated by GraalVM SGXProxyGenerator. */ 

#if defined(__cplusplus)
extern "C" {
#endif

void graalsgx_ecall_relay_Contract(void *param_0, int param_1, int param_2)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_Contract(temp_iso, param_1, param_2);


}

int graalsgx_ecall_relay_add(void *param_0, int param_1, char* param_2, int param_3, int param_4, int param_5)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
int ret = relay_add(temp_iso, param_1, param_2, param_3, param_4, param_5);


return ret;
}

int graalsgx_ecall_relay_countMirrors(void *param_0, int param_1, char* param_2, int param_3)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
int ret = relay_countMirrors(temp_iso, param_1, param_2, param_3);


return ret;
}

int graalsgx_ecall_relay_countNulls(void *param_0, int param_1, char* param_2, int param_3)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
int ret = relay_countNulls(temp_iso, param_1, param_2, param_3);


return ret;
}

void graalsgx_ecall_relay_getAsset(void *param_0, int param_1, char* param_2, int param_3, int param_4)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_getAsset(temp_iso, param_1, param_2, param_3, param_4);


}

int graalsgx_ecall_relay_getRandStringT(void *param_0, int param_1, char* param_2, int param_3, int param_4)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
int ret = relay_getRandStringT(temp_iso, param_1, param_2, param_3, param_4);


return ret;
}

void graalsgx_ecall_relay_greetPeer(void *param_0, int param_1, char* param_2, int param_3, int param_4)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_greetPeer(temp_iso, param_1, param_2, param_3, param_4);


}

void graalsgx_ecall_relay_greetPerson(void *param_0, int param_1, char* param_2, int param_3, int param_4)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_greetPerson(temp_iso, param_1, param_2, param_3, param_4);


}

void graalsgx_ecall_relay_hello(void *param_0, int param_1, char* param_2, int param_3, char* param_4, int param_5)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_hello(temp_iso, param_1, param_2, param_3, param_4, param_5);


}

void graalsgx_ecall_relay_initLedger(void *param_0, int param_1, char* param_2, int param_3)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_initLedger(temp_iso, param_1, param_2, param_3);


}

void graalsgx_ecall_relay_ledger_init(void *param_0, int param_1, char* param_2, int param_3)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_ledger_init(temp_iso, param_1, param_2, param_3);


}

int graalsgx_ecall_relay_sendGreetings(void *param_0, int param_1, char* param_2, int param_3)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
int ret = relay_sendGreetings(temp_iso, param_1, param_2, param_3);


return ret;
}

void graalsgx_ecall_relay_transferAsset(void *param_0, int param_1, char* param_2, int param_3, char* param_4, int param_5, int param_6, int param_7)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_transferAsset(temp_iso, param_1, param_2, param_3, param_4, param_5, param_6, param_7);


}

void graalsgx_ecall_relay_Peer(void *param_0, int param_1, char* param_2, int param_3, int param_4)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_Peer(temp_iso, param_1, param_2, param_3, param_4);


}

int graalsgx_ecall_relay_getBalance(void *param_0, int param_1, char* param_2, int param_3)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
int ret = relay_getBalance(temp_iso, param_1, param_2, param_3);


return ret;
}

int graalsgx_ecall_relay_getLedgerHash(void *param_0, int param_1, char* param_2, int param_3)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
int ret = relay_getLedgerHash(temp_iso, param_1, param_2, param_3);


return ret;
}

int graalsgx_ecall_relay_getName(void *param_0, int param_1, char* param_2, int param_3)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
int ret = relay_getName(temp_iso, param_1, param_2, param_3);


return ret;
}

int graalsgx_ecall_relay_getPeerId(void *param_0, int param_1, char* param_2, int param_3)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
int ret = relay_getPeerId(temp_iso, param_1, param_2, param_3);


return ret;
}

void graalsgx_ecall_relay_addAssets(void *param_0, int param_1, char* param_2, int param_3, char* param_4, int param_5)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_addAssets(temp_iso, param_1, param_2, param_3, param_4, param_5);


}

void graalsgx_ecall_relay_sayMyName(void *param_0, int param_1, char* param_2, int param_3, char* param_4, int param_5)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_sayMyName(temp_iso, param_1, param_2, param_3, param_4, param_5);


}

void graalsgx_ecall_relay_setBalance(void *param_0, int param_1, char* param_2, int param_3, int param_4)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_setBalance(temp_iso, param_1, param_2, param_3, param_4);


}

void graalsgx_ecall_relay_stringTest(void *param_0, int param_1, char* param_2, int param_3, char* param_4, int param_5, int param_6)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_stringTest(temp_iso, param_1, param_2, param_3, param_4, param_5, param_6);


}

void graalsgx_ecall_relay_setLedgerhash(void *param_0, int param_1, char* param_2, int param_3, int param_4)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_setLedgerhash(temp_iso, param_1, param_2, param_3, param_4);


}

void graalsgx_ecall_doProxyCleanupIn(void *param_0)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
doProxyCleanupIn(temp_iso);


}

void graalsgx_ecall_relay_sayHello(void *param_0, int param_1, char* param_2, int param_3)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
relay_sayHello(temp_iso, param_1, param_2, param_3);


}

void graalsgx_ecall_mirrorCleanupOut(void *param_0, int param_1)
{/* Do nothing */}
void graalsgx_ecall_mirrorCleanupIn(void *param_0, int param_1)
{

GRAAL_SGX_INFO();
graal_isolatethread_t* temp_iso = global_enc_iso;
mirrorCleanupIn(temp_iso, param_1);


}

#if defined(__cplusplus)
}
#endif
